reference_model_ros2:
  param_pub_freq_hz: 100
  param_pub_state_ddot_topic: "ref_state_ddot"
  param_pub_state_dot_topic: "ref_state_dot"
  param_pub_state_topic: "ref_state"
  param_qos_buffer: 10
  param_sub_topic: "desired_state"
  rt_dt_phi: 0.01
  rt_dt_psi: 0.01
  rt_dt_theta: 0.01
  rt_dt_x: 0.01
  rt_dt_y: 0.01
  rt_dt_z: 0.01
  rt_omega_n_phi: 1.0
  rt_omega_n_psi: 1.0
  rt_omega_n_theta: 1.0
  rt_omega_n_x: 1.0
  rt_omega_n_y: 1.0
  rt_omega_n_z: 1.0
  rt_sat_state_ddot_lower_phi: -100.0
  rt_sat_state_ddot_lower_psi: -100.0
  rt_sat_state_ddot_lower_theta: -100.0
  rt_sat_state_ddot_lower_x: -100.0
  rt_sat_state_ddot_lower_y: -100.0
  rt_sat_state_ddot_lower_z: -100.0
  rt_sat_state_ddot_upper_phi: 100.0
  rt_sat_state_ddot_upper_psi: 100.0
  rt_sat_state_ddot_upper_theta: 100.0
  rt_sat_state_ddot_upper_x: 100.0
  rt_sat_state_ddot_upper_y: 100.0
  rt_sat_state_ddot_upper_z: 100.0
  rt_sat_state_dot_lower_phi: -100.0
  rt_sat_state_dot_lower_psi: -100.0
  rt_sat_state_dot_lower_theta: -100.0
  rt_sat_state_dot_lower_x: -100.0
  rt_sat_state_dot_lower_y: -100.0
  rt_sat_state_dot_lower_z: -100.0
  rt_sat_state_dot_upper_phi: 100.0
  rt_sat_state_dot_upper_psi: 100.0
  rt_sat_state_dot_upper_theta: 100.0
  rt_sat_state_dot_upper_x: 100.0
  rt_sat_state_dot_upper_y: 100.0
  rt_sat_state_dot_upper_z: 100.0
  rt_zeta_phi: 1.0
  rt_zeta_psi: 1.0
  rt_zeta_theta: 1.0
  rt_zeta_x: 1.0
  rt_zeta_y: 1.0
  rt_zeta_z: 1.0
  use_sim_time: false